print("apple")
print("juice")
print("apple""juice")
print("apple", "juice")
print("apple", "juice",sep = '~')
print("apple", "juice",end = ' is ')
print("tasty")
input("What's your favorite juice? ")
print(input("What's your favorite juice? "))
