n = int(input())
i = 1
print(n * i, end = " ")
i +=1
print(n * i, end = " ")
i += 1
print(n * i, end = " ")
i += 1
print(n * i, end = " ")
i += 1
print(n * i, end = " ")
i += 1
print(n * i, end = " ")
i += 1
print(n * i, end = " ")
i += 1
print(n * i, end = " ")
i += 1
print(n * i, end = " ")
i += 1
